export const All_PRODUCT_REQUEST ="All_PRODUCT_REQUEST";
export const All_PRODUCT_SUCCESS ="All_PRODUCT_SUCCESS";
export const All_PRODUCT_FAIL ="All_PRODUCT_FAIL";




export const PRODUCT_DETAILS_SUCCESS ="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL";


export const CLEAR_ERRORS ="CLEAR_ERRORS";